#BOOK SETTINGS
OPENINGBOOK: [{"Name": "Book A", "pgn": "1. e4 e5"},{"Name": "Book B", "pgn": "1. e4 e5 2. f4"}] 
#add the starting point PGNs you want to create repertoires for, with starting point pgns.
#The format for multiple PGNs and chapters looks like this: [{"Name": "Book A", "pgn": "1. e4 e5"},{"Name": "Book B", "pgn": "1. e4 e5 2. f4"}]
LONGTOSHORT: 0
#if you want the chapter ordered from long lines to short lines, instead of short to long, change to "1". Else 0.


#DATABASE SETTINGS
VARIANT: 'standard' 
#Variants to include in the analysis
SPEEDS: ['blitz,rapid,classical,correspondence'] 
#comma separated Formats to include in the analysis
RATINGS: ['1600,1800,2000,2200,2500'] 
#Ratings of the players to include in the analysis
MOVES: 10
#The number of most played moves to search over for the best move (minimum 5)

#MOVE SELECTION SETTINGS
DEPTHLIKELIHOOD: 0.03
#this controls how deep moves and lines are generated. The smaller the number the deeper the lines. Once cumulative line likelihood reaches this probability threshold, no futher continuations will be added (in percentage so 0.0025 = 0.25%)
ALPHA: 0.001
#The larger this number the more likely we are to select moves with less data. This is the confidence interval alpha (EG 0.05 = 95% CI), for deciding the lower bounds of how good a move's winrate is.
MINPLAYRATE: 0.001
#minimum probability of our move being played in a position to be considered as a 'best move' candidate, as a percentage (0.05= 5%)
MINGAMES: 19 
#games where our moves were played this or less than this will be discarded (unless top engine move) (25 = 25 games).
CONTINUATIONGAMES: 10 
# games where moves played this or less than this will not be considered a valid opponent continuation (ie we don't want to be inferring cumulative probability or likely lines from tiny amounts of games/1 game)
DRAWSAREHALF: 0
#if you want to count draws as half a win (0.5 points), for the win rate calculation, select 1. Else 0. With 0 draws will count as as losses for the win rate calculation.


#ENGINE SETTINGS
ENGINEPATH: '/Users/AM/Downloads/BookBuilder-main/stockfish'
#the filepath where the engine is stored on your computer, so it can be accessed.
#It should be wrapped in quotes (eg 'path/path'), and end in the actual engine file (not the folder), so 'C:\Folder\Chess\BookBuilder-main\stockfish15.exe' on Windows or '/Users/User/Downloads/BookBuilder-main/stockfish' on Mac, for example
#Some users reported errors if the engine has _ in the file name.
CAREABOUTENGINE: 0
#care about engine eval of position or engine finishing = 1, dont care = 0. If this is 0 then no engine functionality will work.
ENGINEDEPTH: 20
#RECOMMENDED minimum 20+ ideally 30+ for stable evaluations in the opening phase.
#what depth the engine should evaluate best moves. the higher the depth the longer the evaluation will take.
ENGINEFINISH: 1
#if we want the engine to complete lines upto the cumulative likelihood, where where data from our perspective doesn't meet minimum criteria. For this kind of finishing, 1. Otherwise 0, and lines will end where there's no good human data for one player.
SOUNDNESSLIMIT: -99
#maximum centipawns we are willing to be down in engine eval, provided the winrate is better (-300 = losing by 3 pawns in eval). We never give up a forced mate, however.
MOVELOSSLIMIT: -99
#RECOMMENDED NOT TO GO CLOSER TO 0 THAN -50 BECAUSE ENGINES ARE INCONSISTENT WHEN EVALUATING OPENINGS, ESPECIALLY ON LOW DEPTH.
#maximum centipawns we are willing to lose vs engine analysis pre move to play a higher winrate move. We never give up a forced mate, however.
IGNORELOSSLIMIT: 300
#centipawns advantage above which we won't care if we play a move that hits our loss limit, if it has a higher win rate (is easier to win)
ENGINETHREADS: 1
#Increase this number to speed the engine up. It's how many threads you want the engine to use (check your comp and set 1 if unsure)
#for reference my safemax is 20
ENGINEHASH: 320
#Increase this number to speed the engine up. It's how much hash (RAM) you want the engine to use (check your comp and set to 16 if unsure)
#for reference my safe max is 10240

# Change this to true/false depending if you want to see detailed output in your terminal when running the program
PRINT_INFO_TO_CONSOLE: true
